services:
  - type: web
    name: rightsdesk
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn rightsdesk.wsgi"
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.0"
